# Site settings
title: Mecra
email: mecra@bilkent.edu.tr
copyright: 2014 Mecra
description: "Medya ve Kültürel Çalışmalar Platformu"
keywords: "Medya, Bilkent Üniversitesi, Medya ve Görsel Çalışmalar, Medya ve Tasarim, Haziran Medyası"
baseurl: ""
url: "http://mecra.bilkent.edu.tr"

# Build settings
markdown: kramdown
permalink: pretty

collections:
  issues:
    output: true

exclude: [ACCOUNT_CREDENTIALS, LICENSE]
